# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EbDtdkA6gri94qwgRq2c5MoFozvo5Cmi
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)

df.head()

from google.colab import files

uploaded = files.upload()

import pandas as pd

df1 = pd.read_csv("wc2026_group_stage.csv")

df1.head()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

matches = pd.read_csv("raw_matches.csv")

matches.head()

from google.colab import files

uploaded = files.upload()

import pandas as pd

matches = pd.read_csv("wc2026_group_stage.csv")

matches.head()

matches.columns
matches.shape
matches.head()

matches.columns.tolist()

team_data = matches[[
    "team",
    "opponent",
    "goals_for",
    "goals_against",
    "goal_diff",
    "result",
    "points",
    "is_host"
]].copy()

team_data.head()

host_nations = ["USA", "Mexico", "Canada"]

team_data["host"] = team_data["team"].isin(host_nations)

team_data.head()

team_data.to_csv("wc2026_group_stage.csv", index=False)

print("File saved successfully!")

team_data.head()

host_data = team_data[team_data["host"] == True]

non_host_data = team_data[team_data["host"] == False]

print("Host teams:", len(host_data))
print("Non-host teams:", len(non_host_data))

host_stats = host_data["goals_for"].agg(["mean", "std", "min", "max"])
non_host_stats = non_host_data["goals_for"].agg(["mean", "std", "min", "max"])

print("HOST TEAMS")
print(host_stats)

print("\nNON-HOST TEAMS")
print(non_host_stats)

host_goals = host_data["goals_for"]

n = len(host_goals)
mean_host = host_goals.mean()
sd_host = host_goals.std()
standard_error = sd_host / np.sqrt(n)

confidence_interval = stats.t.interval(
    0.95,
    df=n-1,
    loc=mean_host,
    scale=standard_error
)

print("Host mean goals:", mean_host)
print("95% Confidence Interval:", confidence_interval)

host_goals = host_data["goals_for"]
non_host_goals = non_host_data["goals_for"]

t_stat, p_value = stats.ttest_ind(
    host_goals,
    non_host_goals,
    equal_var=False
)

print("T-statistic:", t_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("Result: Statistically significant difference.")
else:
    print("Result: No statistically significant difference.")

summary = pd.DataFrame({
    "Group": ["Host teams", "Non-host teams"],
    "Mean": [
        host_data["goals_for"].mean(),
        non_host_data["goals_for"].mean()
    ],
    "Standard Deviation": [
        host_data["goals_for"].std(),
        non_host_data["goals_for"].std()
    ],
    "Minimum": [
        host_data["goals_for"].min(),
        non_host_data["goals_for"].min()
    ],
    "Maximum": [
        host_data["goals_for"].max(),
        non_host_data["goals_for"].max()
    ]
})

summary

summary.to_csv("task1_summary.csv", index=False)

print("Summary table saved successfully!")

host_mean = host_data["goals_for"].mean()
non_host_mean = non_host_data["goals_for"].mean()

host_ci = confidence_interval
host_error = host_mean - host_ci[0]

means = [host_mean, non_host_mean]
errors = [host_error, 0]

groups = ["Host teams", "Non-host teams"]

plt.figure(figsize=(8, 5))

plt.bar(
    groups,
    means,
    yerr=errors,
    capsize=5
)

plt.ylabel("Mean Goals Scored")
plt.title("Host vs Non-Host Teams: Mean Goals Scored")

plt.show()